### ISSUE TITLE
Scudo?

### ISSUE THREAD

**Issue by zachriggle** [thestinger/allocator#27]
Any chance you've looked at the Scudo allocator?

http://llvm.org/docs/ScudoHardenedAllocator.html

I'd be curious to hear your thoughts.

**Comment by thestinger** [comment]
Well, note this repository is a very performance-oriented allocator with no regard to security.

For a hardened allocator, it's hard to do better than the OpenBSD malloc design which is the basis for the hardened allocator in CopperheadOS which I documented at https://copperhead.co/android/docs/technical_overview#hardened-allocator. It has fully out-of-line metadata via the per-pool hash table which tracks spans of pages, and then the per-page bitmaps used as the metadata to track free slots within pages for small allocations. There's no reliance on probabilistic mitigations involving keys to protect inline metadata and it has fully reliably detection for `free(not_an_active_malloc_allocation)`. Bitmaps can be very lightweight (1 bit per allocation slot, and allocation sizes start at 8 or 16 bytes) and also make it very easy to pick a random slot, by randomizing the start of the free slot search in a slab, separately from other forms of randomization. Free lists are inherently LIFO + inline metadata.

Thread caching can be done without free lists (jemalloc uses arrays of pointers last time I checked) but thread caching adds quite a lot of determinism unless it's done in a way that's bad for caching like separate queues for allocation and free and even then it's still more determinism and is only batching allocation and free requests, which is great for throughput but bad for latency. OpenBSD malloc doesn't currently do thread caching, only multiple arenas with threads randomly assigned to them.

The Linux kernel's slub allocator is actually not that far away from the OpenBSD malloc design. It has out-of-line page span metadata comparable to the OpenBSD malloc hash table via `struct page`. If it was changed to use bitmaps instead of free lists for tracking free space within page spans (it already has per-page-span free lists, not global), it could basic the baseline security design.
